name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Go App Docker image
      run: docker build ./go-app/ --tag go-app:$(date +%s)
    - name: Build the Node App Docker image
      run: docker build ./nodejs-app/ --tag node-app:$(date +%s)
