name: Go App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-app
    steps:
      - uses: actions/checkout@v3

      - run: env

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
          mongodb-username: supercharge
          mongodb-password: secret
          mongodb-db: supercharge

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: MONGODB_USERNAME=supercharge MONGODB_PASSWORD=secret MONGODB_URL=localhost MONGODB_DATABASE=supercharge go test -v ./...
        env:
          MONGODB_USERNAME: supercharge
          MONGODB_PASSWORD: secret
          MONGODB_URL: localhost
          MONGODB_DATABASE: supercharge


  # build_local:
  #   needs: test
  #   runs-on: self-hosted
  #   defaults:
  #     run:
  #       working-directory: ./go-app
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Build the Go App Docker image
  #     run: docker build . --tag go-app:$(date +%s)
