name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-app
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...


  build_local:
    needs: test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./go-app
    steps:
    - uses: actions/checkout@v3

    - name: Build the Go App Docker image
      run: docker build . --tag go-app:$(date +%s)
