name: Node App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./nodejs-app

    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v3

      - run: env

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
          mongodb-username: supercharge
          mongodb-password: secret
          mongodb-db: supercharge

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: MONGODB_USERNAME=user MONGODB_PASSWORD=password MONGODB_URL=localhost MONGODB_DATABASE=main npm test
        env:
          MONGODB_USERNAME: supercharge
          MONGODB_PASSWORD: secret
          MONGODB_URL: localhost
          MONGODB_DATABASE: supercharge


  # build_local:
  #   needs: test
  #   runs-on: self-hosted
  #   defaults:
  #     run:
  #       working-directory: ./nodejs-app
  #   steps:
  #   - uses: actions/checkout@v3
      
  #   - name: Build the Node App Docker image
  #     run: docker build . --tag node-app:$(date +%s)
